version: '3.4'

networks:
  bot-network:
    driver: bridge

services:
  api:
    container_name: api
    image: ${DOCKER_REGISTRY-}api
    build:
      context: ..
      dockerfile: src/Backend/Api/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - bot-network

  dc.bot:
    container_name: dc-bot
    image: ${DOCKER_REGISTRY-}dcbot
    build:
      context: ..
      dockerfile: src/Discord/DC.Bot/Dockerfile
    depends_on:
      - rabbitmq
    restart: always
    environment:
        - ApiUrl=http://api
        - EvalApiUrl=http://eval-api
    networks:
      - bot-network

  eval.api:
    container_name: eval-api    
    image: ${DOCKER_REGISTRY-}evalapi
    build:
      context: ..
      dockerfile: src/Eval/Eval.Api/Dockerfile
    restart: always
    networks:
      - bot-network

  tg.bot:
    container_name: tg-bot
    image: ${DOCKER_REGISTRY-}tgbot
    build:
      context: ..
      dockerfile: src/Telegram/TG.Bot/Dockerfile
    restart: always
    environment:
        - ApiUrl=http://api
    networks:
      - bot-network

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - bot-network
